### ISSUE TITLE
Error displaying badges

### ISSUE THREAD

**Issue by caike** [codeschool-projects/jQueryBadgesProject#1]
Javascript is broken:

![html_portfolio](https://cloud.githubusercontent.com/assets/10722/21056409/7afda682-be03-11e6-9fd4-27ba412bf14e.jpg)

**Comment by adamfortuna** [comment]
Good catch! We switched the URLs from using the ID to using username, and were redirecting people to the username if they accessed it with the ID. Unfortunately in that redirect we weren't sending over the "callback" parameter, so it was breaking.

This is fixed now, so it should work whether you use your Code School ID in the URL (which is deprecated) or your username.
